### ISSUE TITLE
Hello, I was deeply impressed by your code. Could you please share your paper? I would like to delve deeper into it. Thank you.

### ISSUE THREAD

**Issue by tlyx1030** [Soapony/Wolpertinger_in_Edge_Caching#1]

**Comment by Soapony** [comment]
Thank you for your comment and I appreciate it. Sorry that I'm still working on my paper, once it is done I will upload to here.

**Comment by tlyx1030** [comment]
Okay, thank you very much. Is this code the final version?

**Comment by Soapony** [comment]
Yes, there won't be any change.

**Comment by tlyx1030** [comment]
Okay, thank you very much for your response.
